services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "9000:9000"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - my_network

  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - my_network
    ports:
      - '3306:3306'

  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - "19999:19999"
    restart: always
    networks:
      - my_network
    volumes:
      - /var/lib/netdata
      - /etc/netdata
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9001:9000"  # Можно поменять на другой порт, если 9000 занят
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  portainer_data:
    driver: local
